services:
 ddb:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?db password not set}
   volumes:
     - postgres-data:/var/lib/postgresql/data
 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
   links:
      - "ddb:db"
 mywebapp:
   build:
      dockerfile: src/Dockerfile
   ports:
     - 5000:80
   links:
      - "ddb:db"
   depends_on:
     - ddb
volumes:
 postgres-data:
networks:
  network1:
    name: postgres-net
    external: true
        